### ISSUE TITLE
mlflow error when deploying the app

### ISSUE THREAD

**Issue by ZaheedaT** [GokuMohandas/mlops-course#17]
**"Run '%s' not found" % run_uuid, databricks_pb2.RESOURCE_DOES_NOT_EXIST
mlflow.exceptions.MlflowException: Run '0f2eebfa38674a7b9e38ad443ea8cd64' not found**

![image](https://user-images.githubusercontent.com/43185132/181863012-490fb7c2-e76e-4fb5-a5ce-eaa987d2b383.png)

**Comment by GokuMohandas** [comment]
Hi @ZaheedaT, the lessons are meant to be taken in sequential order and we create many of the artifacts needed in previous lessons so that's why this error is happening.
