### ISSUE TITLE
Dockerfile issues pulling assets from S3 

### ISSUE THREAD

**Issue by ZaheedaT** [GokuMohandas/mlops-course#18]
=> ERROR [12/12] RUN dvc pull                                                                     1.7s
------
 > [12/12] RUN dvc pull:
#17 1.298 WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:

![image](https://user-images.githubusercontent.com/43185132/181863146-5497d87b-06c6-4e35-bfda-89a0c14a8351.png)

**Comment by GokuMohandas** [comment]
Hi @ZaheedaT, the lessons are meant to be taken in sequential order and we create many of the artifacts needed in previous lessons so that's why this error is happening. We create the necessary data assets and version them with DVC in a prior lesson so this Docker lesson won't run properly if you don't follow the previous lessons.

**Comment by ZaheedaT** [comment]
Hi there, I ran all the lessons, out of Docker as well, and still get this error. I ran this whole workflow first
```
python tagifai/main.py load-data
python tagifai/main.py label-data --args-fp="config/args.json"
python tagifai/main.py optimize --args-fp="config/args.json" --study-name="optimization" --num-trials=10
python tagifai/main.py train-model --args-fp="config/args.json" --experiment-name="baselines" --run-name="sgd"
python tagifai/main.py predict-tag --text="Transfer learning with transformers for text classification."
``

**Comment by GokuMohandas** [comment]
Unfortunately those commands only train a model ready for inference and the DVC steps required are not covered in those commands above. The versioning lesson will have the steps required to version and store the data in order for Docker to be able to pull them.

**Comment by ZaheedaT** [comment]
I will try that, 

There's an issue with the Dockerfile, there is no directory called "stores" in the repo

```COPY stores stores

**Comment by ZaheedaT** [comment]
I followed all the steps from https://madewithml.com/courses/mlops/versioning/

Still getting the same error. I'll leave the course here. Thanks

**Comment by GokuMohandas** [comment]
Hi @ZaheedaT , unfortunately MLOps concepts are quit interweaved and cannot be run in isolation. For example, the stores directory is created in a different lesson. You absolutely need to run the course in sequential order for things to work and cannot skip to one of the later lessons.
