### ISSUE TITLE
Getting error while loading projects.json file

### ISSUE THREAD

**Issue by RXL-Rakesh-Sharma** [GokuMohandas/mlops-course#19]
# Load projects
url = "https://raw.githubusercontent.com/GokuMohandas/Made-With-ML/main/datasets/projects.json"
projects = json.loads(urlopen(url).read())
print (f"{len(projects)} projects")
print (json.dumps(projects[0], indent=2))

--------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Input In [15], in <cell line: 3>()
      1 # Load projects
      2 url = "https://raw.githubusercontent.com/GokuMohandas/Made-With-ML/main/datasets/projects.json"
----> 3 projects = json.loads(urlopen(url).read())
      4 print (f"{len(projects)} projects")
      5 print (json.dumps(projects[0], indent=2))

File ~/.conda/envs/Ml_Flow/lib/python3.8/urllib/request.py:222, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220 else:
    221     opener = _opener
--> 222 return opener.open(url, data, timeout)

File ~/.conda/envs/Ml_Flow/lib/python3.8/urllib/request.py:531, in OpenerDirector.open(self, fullurl, data, timeout)
    529 for processor in self.process_response.get(protocol, []):
    530     meth = getattr(processor, meth_name)
--> 531     response = meth(req, response)
    533 return response

File ~/.conda/envs/Ml_Flow/lib/python3.8/urllib/request.py:640, in HTTPErrorProcessor.http_response(self, request, response)
    637 # According to RFC 2616, "2xx" code indicates that the client's
    638 # request was successfully received, understood, and accepted.
    639 if not (200 <= code < 300):
--> 640     response = self.parent.error(
    641         'http', request, response, code, msg, hdrs)
    643 return response

File ~/.conda/envs/Ml_Flow/lib/python3.8/urllib/request.py:569, in OpenerDirector.error(self, proto, *args)
    567 if http_err:
    568     args = (dict, 'default', 'http_error_default') + orig_args
--> 569     return self._call_chain(*args)

File ~/.conda/envs/Ml_Flow/lib/python3.8/urllib/request.py:502, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    500 for handler in handlers:
    501     func = getattr(handler, meth_name)
--> 502     result = func(*args)
    503     if result is not None:
    504         return result

File ~/.conda/envs/Ml_Flow/lib/python3.8/urllib/request.py:649, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    648 def http_error_default(self, req, fp, code, msg, hdrs):
--> 649     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 404: Not Found

**Comment by GokuMohandas** [comment]
Hi @RXL-Rakesh-Sharma , I apologize for the error. I was making some changes yesterday and accidentally deleted the original data files. I'll push the fixes today!
