### ISSUE TITLE
typo in pre-commit package link

### ISSUE THREAD

**Issue by rigid-logician** [GokuMohandas/mlops-course#21]
https://github.com/GokuMohandas/mlops-course/blob/a009e309ef7dc4a6e6254ee4d733f3baa6dd74ca/.pre-commit-config.yaml#L26

"gitlab" -> "github"

**Comment by GokuMohandas** [comment]
Hi @rigid-logician, thanks for telling me about this, I didn't realize they [migrated](https://github.com/PyCQA/flake8/issues/1290) to GitHub. Now I can remove the only GitLab link from all my precommit hooks!
