### ISSUE TITLE
MLFlow Dashboard from Colab not showing

### ISSUE THREAD

**Issue by benitomartin** [GokuMohandas/mlops-course#26]
By Running the MLFlow cell from Colab to see the dashboard...

```
get_ipython().system_raw("mlflow server -h 0.0.0.0 -p 8000 --backend-store-uri $PWD/experiments/ &")
!npx localtunnel --port 8000
```

...I get an URL like this: 

https://sixty-kiwis-chew.loca.lt/

When I click, I'm redirected to a page that asks me for an Endpoint IP. 

![image](https://github.com/GokuMohandas/mlops-course/assets/116911431/08781ccb-77a0-456f-8d75-de14c7dc0970)

I got the IP by running the following code 

`!wget -q -O - ipv4.icanhazip.com`

or this

`!curl ipv4.icanhazip.com`

However, it does not work. How can I run the code in Colab to see the Dashboard of MLFlow?

**Comment by GokuMohandas** [comment]
Hey @benitomartin, a lot of improvements are coming to the course in two weeks and these issues are all addressed. I would recommend just running the entire notebook + mlflow dashboard locally for now. Localtunnel used to be a free service but now they are charging so that why you see this message.
